name: renovate-merge-bot
description: Auto-merge Renovate pull requests in GitHub Actions

inputs:
  github-app-id:
    description: GitHub App ID
    required: true
  github-app-private-key:
    description: GitHub App private key
    required: true
  dry-run:
    description: Set true to dry-run
    required: true
    default: false

runs:
  using: 'node20'
  main: 'dist/index.js'
