name: typescript-action
description: Template of TypeScript Action

inputs:
  github-app-id:
    description: GitHub App ID
    required: true
  github-app-private-key:
    description: GitHub App private key
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
