import type { ListPullRequestQuery } from '../../src/generated/graphql.js'
import { MergeableState, PullRequestMergeMethod, StatusState } from '../../src/generated/graphql-types.js'

/*
https://docs.github.com/en/graphql/overview/explorer

{
  "owner": "int128",
  "repo": "list-associated-pull-requests-action"
}
*/
export const payload: ListPullRequestQuery = {
  repository: {
    owner: {
      login: 'int128',
    },
    name: 'list-associated-pull-requests-action',
    viewerDefaultMergeMethod: PullRequestMergeMethod.Squash,
    pullRequests: {
      nodes: [
        {
          id: 'PR_kwDOG4DTyM5N-piU',
          number: 382,
          author: {
            login: 'renovate',
          },
          mergeable: MergeableState.Mergeable,
          bodyText:
            "This PR contains the following updates:\n\n\n\nPackage\nChange\nAge\nAdoption\nPassing\nConfidence\n\n\n\n\n@octokit/graphql-schema\n13.3.0 -> 14.4.0\n\n\n\n\n\n\n\n\nRelease Notes\n\noctokit/graphql-schema\nv14.4.0\nCompare Source\nFeatures\n\nmerge queue and graphql type additions (#​752) (6275088)\n\nv14.3.0\nCompare Source\nFeatures\n\nadditional sponsorship fields (#​750) (14c09f5)\n\nv14.2.0\nCompare Source\nFeatures\n\nsupport merge queue operations (#​749) (ec873ef)\n\nv14.1.0\nCompare Source\nFeatures\n\nRepository#archivedAt (#​748) (fba4e60)\n\nv14.0.0\nCompare Source\n\nBreaking change: remove fixReason, add notificationSetting (#​745) (036af2b), closes #​745\n\nBREAKING CHANGES\n\n\n\nWIP: schema.graphql changed - please review\n\n\n\nbuild: schema.json and schema.d.ts updated\n\n\nTrigger test step\n\n\nv13.10.0\nCompare Source\nFeatures\n\nschema: remove 'fixReason' from RepositoryVulnerabilityAlerts (#​744) (2465a14)\n\nv13.9.1\nCompare Source\nBug Fixes\n\nreplace interfaces with implementing types (#​738) (bbcdd33), closes #​526\n\nv13.9.0\nCompare Source\nFeatures\n\nmultiple new types across a few weeks of updates (#​735) (6b11fa5)\n\nv13.7.0\nCompare Source\nFeatures\n\nActor#socialAccounts, ProjectV2#template (#​731) (706f2d1)\n\nv13.6.0\nCompare Source\nFeatures\n\nWorkflowRun#event, BranchProtectionRule#{requiredDeploymentEnvironments,requiresDeployments} inputs for mutations  (#​730) (0a6f39f)\n\nv13.5.0\nCompare Source\nFeatures\n\nMutations: createProjectV2Field, deleteProjectV2Field (#​727) (46d2508)\n\nv13.4.0\nCompare Source\nFeatures\n\nProjectV2ViewLayout#ROADMAP_LAYOUT (#​725) (73cf68b)\n\nv13.3.2\nCompare Source\nBug Fixes\n\nbuild files update (#​724) (7f9cad9)\n\nv13.3.1\nCompare Source\nBug Fixes\n\nbuild files update (#​723) (35f23b5)\n\n\n\nConfiguration\n📅 Schedule: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).\n🚦 Automerge: Disabled by config. Please merge this manually once you are satisfied.\n♻ Rebasing: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n🔕 Ignore: Close this PR and you won't be reminded about this update again.\n\n\n If you want to rebase/retry this PR, check this box\n\n\nThis PR has been generated by Mend Renovate. View repository job log here.",
          headRef: {
            name: 'renovate/octokit-graphql-schema-14.x',
            target: {
              __typename: 'Commit',
              oid: 'f3bfa9cdcd779370164d7756ef889325ffadd938',
              tree: {
                oid: '400a326555a92be4b755055c4203195eb4fda010',
              },
              committedDate: '2023-04-30T09:47:00Z',
              committer: {
                user: {
                  login: 'renovate[bot]',
                },
              },
              statusCheckRollup: {
                state: StatusState.Pending,
              },
            },
          },
        },
        {
          id: 'PR_kwDOG4DTyM5KR8Ys',
          number: 343,
          author: {
            login: 'renovate',
          },
          mergeable: MergeableState.Conflicting,
          bodyText:
            "This PR contains the following updates:\n\n\n\nPackage\nChange\nAge\nAdoption\nPassing\nConfidence\n\n\n\n\n@octokit/graphql-schema\n13.3.0 -> 13.7.0\n\n\n\n\n\n\n\n\nRelease Notes\n\noctokit/graphql-schema\nv13.7.0\nCompare Source\nFeatures\n\nActor#socialAccounts, ProjectV2#template (#​731) (706f2d1)\n\nv13.6.0\nCompare Source\nFeatures\n\nWorkflowRun#event, BranchProtectionRule#{requiredDeploymentEnvironments,requiresDeployments} inputs for mutations  (#​730) (0a6f39f)\n\nv13.5.0\nCompare Source\nFeatures\n\nMutations: createProjectV2Field, deleteProjectV2Field (#​727) (46d2508)\n\nv13.4.0\nCompare Source\nFeatures\n\nProjectV2ViewLayout#ROADMAP_LAYOUT (#​725) (73cf68b)\n\nv13.3.2\nCompare Source\nBug Fixes\n\nbuild files update (#​724) (7f9cad9)\n\nv13.3.1\nCompare Source\nBug Fixes\n\nbuild files update (#​723) (35f23b5)\n\n\n\nConfiguration\n📅 Schedule: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).\n🚦 Automerge: Enabled.\n♻ Rebasing: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n🔕 Ignore: Close this PR and you won't be reminded about this update again.\n\n\n If you want to rebase/retry this PR, check this box\n\n\nThis PR has been generated by Mend Renovate. View repository job log here.",
          headRef: {
            name: 'renovate/octokit-graphql-schema-13.x',
            target: {
              __typename: 'Commit',
              oid: 'b0b7c9d1fe30a21662c62f809ce064ffef986120',
              tree: {
                oid: '8531bcd12dabf62565228111dc7028f29eddb682',
              },
              committedDate: '2023-03-11T23:58:14Z',
              committer: {
                user: {
                  login: 'github-actions[bot]',
                },
              },
              statusCheckRollup: null,
            },
          },
        },
        {
          id: 'PR_kwDOG4DTyM44opIm',
          number: 98,
          author: {
            login: 'int128',
          },
          mergeable: MergeableState.Mergeable,
          bodyText: '',
          headRef: {
            name: 'test-fixture-head',
            target: {
              __typename: 'Commit',
              oid: '0f9bbfade221f8b590163c664e27c3839fffd3c8',
              tree: {
                oid: '061bbed3cbd6e76a6ddaf4cdb84e0711b2c658b6',
              },
              committedDate: '2022-05-28T23:41:47Z',
              committer: {
                user: {
                  login: 'renovate[bot]',
                },
              },
              statusCheckRollup: {
                state: StatusState.Success,
              },
            },
          },
        },
      ],
    },
  },
}
