name: run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  renovate-merge-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/renovate-merge-bot@8567c5185a9935164f0e60ecb176ce23a45541f8 # v1.44.0
        with:
          github-app-id: ${{ secrets.BOT_APP_ID }}
          github-app-private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
