name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - action.yaml
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn package

      - name: Run int128/renovate-merge-bot
        uses: ./
        with:
          github-app-id: ${{ secrets.BOT_APP_ID }}
          github-app-private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          dry-run: true

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 20
          cache: yarn
      - run: yarn
      - run: yarn lint --fix
      - run: yarn format
      - run: yarn graphql-codegen
      - uses: int128/update-generated-files-action@639edeb9da21ea3fd33e40c7ffcd442f224d1e8c # v2.42.0
